### ISSUE TITLE
[bug] labelled map and/or mask and/or statistic map inconsistent result

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-python#368] opened 2023-05-03 13:01 UTC
as of [v0.4a47](https://github.com/FZJ-INM1-BDA/siibra-python/tree/v0.4a47)

min code to reproduce:

```python

MNI152_ID="minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2"
COLIN_ID="minds/core/referencespace/v1.0.0/7f39f7be-445b-47c0-9791-e971c0b6d992"

JBA_29_ID="minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290"
JBA_30_ID="minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-300"

HOC1_RIGHT="Area hOc1 (V1, 17, CalcS) - right hemisphere"
FP1_RIGHT="Area Fp1 (FPole) - right hemisphere"

STATISTIC_ENDPOINT="statistical"
LABELLED_ENDPOINT="labelled"

map_shape_args = product(
    ((MNI152_ID, (193, 229, 193)),),
    (JBA_29_ID,),
    (STATISTIC_ENDPOINT, LABELLED_ENDPOINT),
    (HOC1_RIGHT, FP1_RIGHT, None),
)

@pytest.mark.parametrize('space_shape,parc_id,map_endpoint,region_name', map_shape_args)
def test_map_shape(space_shape,parc_id,map_endpoint,region_name):
    if region_name is None and map_endpoint == STATISTIC_ENDPOINT:
        assert True
        return
    space_id, expected_shape = space_shape
    
    volume_data = None
    if region_name is not None:
        region = siibra.get_region(parc_id, region_name)
        volume_data = region.fetch_regional_map(space_id, map_endpoint)
    else:
        labelled_map = siibra.get_map(parc_id, space_id, map_endpoint)
        assert labelled_map is not None
        volume_data = labelled_map.fetch()
    
    assert volume_data
    assert volume_data.get_fdata().shape == expected_shape, f"{volume_data.get_fdata().shape}, {expected_shape}, {region_name}, {map_endpoint}, {space_id}"

```

You may have to run a few times to see the assertion error. see https://github.com/FZJ-INM1-BDA/siibra-python/actions/runs/4871591123

particularly e2e succeeding in py3.9 but failing in py3.10

expected: returned nifti shape to be consistent

maybe related to https://github.com/FZJ-INM1-BDA/siibra-python/issues/318

**Comment by AhmetNSimsek** [comment] 2023-05-10 15:16
`fetch_regional_map` fetches the map by  `m.fetch(region=self, format='image')`. If  `format='image'` is set, `volume.fetch` uses `requested_formats = set(Volume.SUPPORTED_FORMATS) - set(Volume.MESH_FORMATS)` which then ignores the predefined order,
`IMAGE_FORMATS = ["nii", "zip/nii", "neuroglancer/precomputed"]`, and returns `{'neuroglancer/precomputed', 'nii', 'zip/nii'}`.

I pushed a fix (df51a05cbe7a3384fb69aa2f9676de807da46ae9) and I am yet to reproduce the issue. I will run the tests on github several times.

**Comment by xgui3783** [comment] 2023-05-10 16:15
> `fetch_regional_map` fetches the map by `m.fetch(region=self, format='image')`. If `format='image'` is set, `volume.fetch` uses `requested_formats = set(Volume.SUPPORTED_FORMATS) - set(Volume.MESH_FORMATS)` which then ignores the predefined order, `IMAGE_FORMATS = ["nii", "zip/nii", "neuroglancer/precomputed"]`, and returns `{'neuroglancer/precomputed', 'nii', 'zip/nii'}`.
> 
> I pushed a fix ([df51a05](https://github.com/FZJ-INM1-BDA/siibra-python/commit/df51a05cbe7a3384fb69aa2f9676de807da46ae9)) and I am yet to reproduce the issue. I will run the tests on github several times.

this likely won't solve the issue in an event of network error. see https://github.com/FZJ-INM1-BDA/siibra-python/issues/318 (which, in hind sight, is really probably the same issue)

**Comment by AhmetNSimsek** [comment] 2023-05-10 16:48
Agreed. I'm dissecting as I go.

**Comment by AhmetNSimsek** [comment] 2023-05-11 11:06
Using df51a05cbe7a3384fb69aa2f9676de807da46ae9, I cannot reproduce #318. I always get 6203.

**Comment by xgui3783** [comment] 2023-05-11 11:44
> Using [df51a05](https://github.com/FZJ-INM1-BDA/siibra-python/commit/df51a05cbe7a3384fb69aa2f9676de807da46ae9), I cannot reproduce #318. I always get 6203.

If the comment concerns #318, can you comment on #318?

**Closed** 2023-06-01 13:48 UTC
Labels: bug, important, urgent
