### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by MSenden** [FZJ-INM1-BDA/siibra-python#14] opened 2021-04-21 09:51 UTC
Hi,

I tried to install siibra using pip on two separate systems (Ubuntu 20.04 and Windows 10 both using Python coming with Anaconda). In both cases, the installation process exists with errors.

From my Ubuntu system:
```Building wheels for collected packages: psutil, posix-ipc
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/mario/anaconda3/envs/hbpatlas/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5f77gmol
       cwd: /tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_exceptions.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.8/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.8/psutil
  creating build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.8/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.8/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/psutil
  gcc -pthread -B /home/mario/anaconda3/envs/hbpatlas/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/mario/anaconda3/envs/hbpatlas/include/python3.8 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.8/psutil/_psutil_common.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
  Building wheel for posix-ipc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/mario/anaconda3/envs/hbpatlas/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r42v1ccb/posix-ipc_be0f64e0767d45f49caaff0f1cfc8c1a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r42v1ccb/posix-ipc_be0f64e0767d45f49caaff0f1cfc8c1a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ne9azowm
       cwd: /tmp/pip-install-r42v1ccb/posix-ipc_be0f64e0767d45f49caaff0f1cfc8c1a/
  Complete output (23 lines):
  ******************************************************************************
  * Setup can't determine if it needs to link to the realtime libraries on your
  * system, so it will default to 'no' which may not be correct.
  *
  * Please report this message and your operating system info to the package
  * maintainer listed in the README file.
  ******************************************************************************
  ******************************************************************************
  * Setup can't determine the value of PAGE_SIZE on your system, so it will
  * default to 4096 which may not be correct.
  *
  * Please report this message and your operating system info to the package
  * maintainer listed in the README file.
  ******************************************************************************
  running bdist_wheel
  running build
  running build_ext
  building 'posix_ipc' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  gcc -pthread -B /home/mario/anaconda3/envs/hbpatlas/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mario/anaconda3/envs/hbpatlas/include/python3.8 -c posix_ipc_module.c -o build/temp.linux-x86_64-3.8/posix_ipc_module.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for posix-ipc
  Running setup.py clean for posix-ipc
Failed to build psutil posix-ipc
Installing collected packages: psutil, posix-ipc, patsy, pandas, nibabel, networkx, matplotlib, json5, imageio, fpzip, fastremap, DracoPy, compressed-segmentation, cloud-files, args, statsmodels, scikit-image, python-gitlab, nilearn, memoization, cloud-volume, clint, appdirs, anytree
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /home/mario/anaconda3/envs/hbpatlas/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n2s2go14/install-record.txt --single-version-externally-managed --compile --install-headers /home/mario/anaconda3/envs/hbpatlas/include/python3.8/psutil
         cwd: /tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/
    Complete output (41 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_exceptions.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.8/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.8/psutil
    creating build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.8/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.8/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/psutil
    gcc -pthread -B /home/mario/anaconda3/envs/hbpatlas/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/mario/anaconda3/envs/hbpatlas/include/python3.8 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.8/psutil/_psutil_common.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mario/anaconda3/envs/hbpatlas/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r42v1ccb/psutil_1bc071388f984cd48c81348fa3ceeec2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n2s2go14/install-record.txt --single-version-externally-managed --compile --install-headers /home/mario/anaconda3/envs/hbpatlas/include/python3.8/psutil Check the logs for full command output.```

**Comment by xgui3783** [comment] 2021-04-22 08:04
I can reproduce in venv when installing from source with similar errors:

environment:

```sh
> python --version
Python 3.6.9
> pip --version
pip 21.0.1 from /home/xiao/dev/projects/siibra-python/venv/lib/python3.6/site-packages/pip (python 3.6)
```

log:

```sh
... (removed for brevity)
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /home/xiao/dev/projects/siibra-python/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d60kb1sa/psutil_281605eff95f48fc8cc687760ed5476e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d60kb1sa/psutil_281605eff95f48fc8cc687760ed5476e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t2brcczi/install-record.txt --single-version-externally-managed --compile --install-headers /home/xiao/dev/projects/siibra-python/venv/include/site/python3.6/psutil
         cwd: /tmp/pip-install-d60kb1sa/psutil_281605eff95f48fc8cc687760ed5476e/
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_exceptions.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    creating build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -I/home/xiao/dev/projects/siibra-python/venv/include -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/xiao/dev/projects/siibra-python/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d60kb1sa/psutil_281605eff95f48fc8cc687760ed5476e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d60kb1sa/psutil_281605eff95f48fc8cc687760ed5476e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t2brcczi/install-record.txt --single-version-externally-managed --compile --install-headers /home/xiao/dev/projects/siibra-python/venv/include/site/python3.6/psutil Check the logs for full command output.
```

**Comment by xgui3783** [comment] 2021-04-22 08:23
for me, it turns out that I needed to install `python-dev` package [link](https://github.com/giampaolo/psutil/issues/1143#issuecomment-334694641)

specificially:

```sh
> sudo apt-get install python3.6-dev
```

The question remains, if python header file is a hard requirement

**Comment by dickscheid** [comment] 2021-04-22 19:39
I couldn't reproduce on my ubuntu system, I guess it's indeed the python-dev package that is missing. I will check which of our imports requires the psutil package, it's not a first order requirement of siibra.

**Comment by dickscheid** [comment] 2021-04-22 19:49
The psutil is one of the many dependencies of cloudvolume, which siibra uses for BigBrain support. So there is no way around at the moment, except we make BigBrain support optional so that a simple install ignore cloudvolume and the extended BigBrain features in case the package is not available.

**Comment by EtienneCmb** [comment] 2021-04-23 06:07
Hi everyone,

I successfully installed siibra through pip but once I import it I've this BigBrain related issue :

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-cbda084591b0> in <module>
----> 1 import siibra
      2 siibra.logger.setLevel('INFO')
      3 from nilearn import plotting

~/anaconda3/lib/python3.7/site-packages/siibra/__init__.py in <module>
     27 from os import path
     28 
---> 29 from .space import REGISTRY as spaces
     30 from .parcellation import REGISTRY as parcellations
     31 from .atlas import REGISTRY as atlases

~/anaconda3/lib/python3.7/site-packages/siibra/space.py in <module>
     16 from .config import ConfigurationRegistry
     17 from .retrieval import download_file
---> 18 from .bigbrain import BigBrainVolume
     19 from . import logger
     20 import nibabel as nib

~/anaconda3/lib/python3.7/site-packages/siibra/bigbrain.py in <module>
     20 import json
     21 import numpy as np
---> 22 from cloudvolume import CloudVolume,Bbox
     23 from memoization import cached
     24 import nibabel as nib

~/anaconda3/lib/python3.7/site-packages/cloudvolume/__init__.py in <module>
     72 
     73 # Register plugins
---> 74 from .datasource.precomputed import register as register_precomputed
     75 from .datasource.graphene import register as register_graphene
     76 

~/anaconda3/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/__init__.py in <module>
----> 1 from .image import PrecomputedImageSource
      2 from .metadata import PrecomputedMetadata
      3 from .mesh import PrecomputedMeshSource
      4 from .skeleton import PrecomputedSkeletonSource
      5 

~/anaconda3/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/__init__.py in <module>
     25 from .. import sharding
     26 from .common import chunknames, gridpoints, compressed_morton_code
---> 27 from . import tx, rx
     28 
     29 class PrecomputedImageSource(ImageSourceInterface):

~/anaconda3/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/tx.py in <module>
     29   should_compress
     30 )
---> 31 from .rx import download_chunks_threaded
     32 
     33 def upload(

~/anaconda3/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/rx.py in <module>
     10 
     11 from cloudfiles import reset_connection_pools, CloudFiles, compression
---> 12 import fastremap
     13 
     14 from ....exceptions import EmptyVolumeException, EmptyFileException

fastremap.pyx in init fastremap()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by dickscheid** [comment] 2021-04-23 06:26
Hi Etienne,

his is a known incompatibility of numpy with one of our imported packages, and not specific to siibra.. It happened to others previously, and you typically just need to update or reinstall numpy to have the latest version, see e.g. [here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp). Let me know if that helped.

Timo

**Comment by EtienneCmb** [comment] 2021-04-23 06:29
Hi @dickscheid, updating NumPy fix my issue. Thanks !

**Comment by dickscheid** [comment] 2021-04-23 06:30
@EtienneCmb , if you manage to send me the previous and new version of numpy that you used, I will possibly update the requirements regarding the numpy version to avoid this in the future.

**Comment by EtienneCmb** [comment] 2021-04-23 06:32
Yes, I was using **numpy 1.19.2** and update to **numpy 1.20.2**

**Comment by dickscheid** [comment] 2021-05-10 14:41
@xgui3783 @MSenden is this resolved by install python-dev on the system?

**Comment by MSenden** [comment] 2021-05-18 08:29
for me it solved the issue as well. Thanks!

**Closed** 2021-05-18 21:20 UTC
